spinup_start: 1998-01-01
start_date: 1998-03-01
end_date: 1998-12-31
subcatchmentpath: runs
parameter_ranges: parameter_ranges.csv
gpus: 0
monthly: true
forward: true

observed_data:
  path: observations.csv
  column: flow

options:
  define_first_run: False

DEAP:
  use_multiprocessing: True
  maximize: True
  ngen: 3 # 10
  mu: 10 # 120
  lambda_: 3 # 24
  select_best: 3