spinup_start: 2003-01-01
start_date: 2004-01-01
end_date: 2006-01-01
timeperiod: daily
subcatchmentpath: runs
parameter_ranges: parameter_ranges.csv
gpus: 2

observed_data:
  path: observations.csv
  column: flow

options:
  define_first_run: False

DEAP:
  use_multiprocessing: True
  maximize: True
  ngen: 3 # 10
  mu: 24 # 120
  lambda_: 8 # 24
  select_best: 10