start_date: 2000-01-01
end_date: 2000-01-03
timeperiod: daily
subcatchmentpath: runs
parameter_ranges: parameter_ranges.csv
scenario: base

observed_data:
  path: observations.csv
  column: flow

options:
  define_first_run: False
  redo_best_run: True

DEAP:
  use_multiprocessing: false
  pool_limit: 5
  maximize: True
  ngen: 2
  mu: 5 # 256
  lambda_: 2 # 32
 