spinup_start: 2004-01-01
start_date: 2006-01-01
end_date: 2012-01-01
subcatchmentpath: runs
parameter_ranges: parameter_ranges.csv
gpus: 2
monthly: true
forward: true

observed_data:
  path: observations.csv
  column: flow

options:
  define_first_run: False

DEAP:
  use_multiprocessing: True
  maximize: True
  ngen: 10 # 10
  mu: 60 # 120
  lambda_: 12 # 24
  select_best: 10