spinup_start: 2003-01-01
start_date: 2006-01-01
end_date: 2010-12-31
timeperiod: daily
subcatchmentpath: runs
parameter_ranges: parameter_ranges.csv

observed_data:
  path: observations.csv
  column: flow

options:
  define_first_run: False
  redo_best_run: True

DEAP:
  use_multiprocessing: true
  maximize: True
  ngen: 3
  mu: 24 # 256
  lambda_: 12 # 32
 