# Snakemake profile for GEB calibration workflow

# Workflow file
snakefile: workflow/Snakefile_calibrate

# Configuration
configfile: workflow/config/calibrate.yml

# Execution settings
cores: all
use-conda: false

# Output settings
printshellcmds: true
show-failed-logs: true

# Resource settings
default-resources:
  - mem_mb=4000
  - disk_mb=10000
  - tmpdir="/tmp"

# Restart settings
rerun-incomplete: true
keep-going: false

# Reporting
# report: reports/calibration_report.html
