setup_grid:
  hydrography_fn: merit_hydro_30sec
  basin_index_fn: merit_hydro_index
  sub_grid_factor: 20

setup_cell_area:

setup_regions_and_land_use:
  region_database: gadm_level1
  ISO3_column: GID_0
  unique_region_id: UID
  river_threshold: 100

setup_economic_data:

setup_mannings:

setup_channel_width:
  minimum_width: 3

setup_channel_depth:

setup_channel_ratio:

setup_elevation:

setup_soil_parameters:

setup_land_use_parameters:

setup_waterbodies:
  command_areas: null
  custom_reservoir_capacity: null

setup_water_demand:
  starttime: 1961-01-01
  endtime: 2060-12-31
  ssp: ssp2

setup_groundwater:

setup_well_prices_by_reference_year_global:
  WHY_10: 82.0209974 # $/m
  WHY_20: 164 # $/m
  WHY_30: 50 # $/m
  reference_year: 2017
  start_year: 1960
  end_year: 2020

setup_irrigation_sources:
  irrigation_sources:
    "no": -1
    canal: 0
    well: 1

setup_create_farms_simple:

setup_crops_from_source:
  source: MIRCA2000

setup_farmer_characteristics_simple:
  risk_aversion_mean: 2
  risk_aversion_standard_deviation: 1
  discount_rate: 0.05
  interest_rate: 0.05
  irrigation_choice:
    canal: 80
    well: 20

setup_cultivation_costs:
  cultivation_costs: 0

setup_crop_prices:
  crop_prices: 200

setup_population:

setup_assets:
  feature_types:
  - buildings
  - roads
  - rails

setup_damage_parameters:
  parameters:
    flood:
      land_use:
        forest:
          curve:
            - [0, 0]
            - [0.1, 0.1]
            - [0.25, 0.3]
            - [0.50, 0.55]
            - [1.00, 0.65]
            - [1.50, 0.7]
            - [2.00, 0.9]
            - [2.50, 0.92]
            - [3.00, 0.95]
            - [4.00, 1.00]
            - [5.00, 1.00]
          maximum_damage: 10.79
        agriculture:
          curve:
            - [0, 0]
            - [0.1, 0.1]
            - [0.25, 0.3]
            - [0.50, 0.55]
            - [1.00, 0.65]
            - [1.50, 0.7]
            - [2.00, 0.9]
            - [2.50, 0.92]
            - [3.00, 0.95]
            - [4.00, 1.00]
            - [5.00, 1.00]
          maximum_damage: 1.83
      buildings:
        structure:
          curve:
            - [0, 0]
            - [0.1, 0.27]
            - [0.5, 0.35]
            - [1, 0.37]
            - [1.5, 0.42]
            - [2, 0.45]
            - [2.5, 0.47]
            - [3, 0.5]
          maximum_damage: 1806
         
        content:
          curve:
            - [0, 0]
            - [0.10, 0.5]
            - [0.50, 0.55]
            - [1.00, 0.6]
            - [1.50, 0.65]
            - [2.00, 0.67]
            - [2.50, 0.7]
            - [3.00, 0.72]
          maximum_damage: 78787
      rail:
        main:
          curve:
            - [0, 0]
            - [0.05, 0.02]
            - [0.20, 0.2]
            - [1.40, 1]
            - [6.00, 1]
          maximum_damage: 7022
      road:
        residential:
          curve:
            - [0, 0]
            - [0.50, 0.015]
            - [1.00, 0.025]
            - [1.50, 0.03]
            - [2.00, 0.035]
            - [6.00, 0.05]
          maximum_damage: 5
        unclassified:
          curve:
            - [0, 0]
            - [0.50, 0.015]
            - [1.00, 0.025]
            - [1.50, 0.03]
            - [2.00, 0.035]
            - [6.00, 0.05]
          maximum_damage: 5
        tertiary:
          curve:
            - [0, 0]
            - [0.50, 0.015]
            - [1.00, 0.025]
            - [1.50, 0.03]
            - [2.00, 0.035]
            - [6.00, 0.05]
          maximum_damage: 10
        primary:
          curve:
            - [0, 0]
            - [0.50, 0.015]
            - [1.00, 0.025]
            - [1.50, 0.03]
            - [2.00, 0.035]
            - [6.00, 0.05]
          maximum_damage: 50
        secondary:
          curve:
            - [0, 0]
            - [0.50, 0.015]
            - [1.00, 0.025]
            - [1.50, 0.03]
            - [2.00, 0.035]
            - [6.00, 0.05]
          maximum_damage: 25
        motorway:
          curve:
            - [0, 0]
            - [0.50, 0.01]
            - [1.00, 0.03]
            - [1.50, 0.075]
            - [2.00, 0.1]
            - [6.00, 0.2]
          maximum_damage: 4000
        motorway_link:
          curve:
            - [0, 0]
            - [0.50, 0.01]
            - [1.00, 0.03]
            - [1.50, 0.075]
            - [2.00, 0.1]
            - [6.00, 0.2]
          maximum_damage: 4000
        trunk:
          curve:
            - [0, 0]
            - [0.50, 0.01]
            - [1.00, 0.03]
            - [1.50, 0.075]
            - [2.00, 0.1]
            - [6.00, 0.2]
          maximum_damage: 1000
        trunk_link:
          curve:
            - [0, 0]
            - [0.50, 0.01]
            - [1.00, 0.03]
            - [1.50, 0.075]
            - [2.00, 0.1]
            - [6.00, 0.2]
          maximum_damage: 1000
        primary_link:
          curve:
            - [0, 0]
            - [0.50, 0.015]
            - [1.00, 0.025]
            - [1.50, 0.03]
            - [2.00, 0.035]
            - [6.00, 0.05]
          maximum_damage: 50
        secondary_link:
          curve:
            - [0, 0]
            - [0.50, 0.015]
            - [1.00, 0.025]
            - [1.50, 0.03]
            - [2.00, 0.035]
            - [6.00, 0.05]
          maximum_damage: 25

setup_forcing:
  data_source: era5
  starttime: 2000-01-01
  endtime: 2023-12-31

setup_SPEI:
  calibration_period_start: 2000-01-01
  calibration_period_end: 2020-12-31
