# GEB Calibration Workflow Configuration

# Region to calibrate
REGION: geul

# Output directory
BASE_DIR: tests/tmp/snakemake/calibrate/geul

# Evolutionary algorithm parameters
NGEN: 5          # Number of generations
MU: 10           # Population size for generation 0
LAMBDA: 20       # Offspring size for subsequent generations
SEED: 42         # Random seed for reproducibility

# Parameters to calibrate
# Each parameter should have min and max bounds
PARAMETERS:
  param1:
    min: 0.0
    max: 1.0
    description: "Example parameter 1"
  param2:
    min: 0.0
    max: 1.0
    description: "Example parameter 2"

# DEAP algorithm configuration
DEAP:
  crossover_prob: 0.7      # Probability of crossover
  mutation_prob: 0.3       # Probability of mutation
  blend_alpha: 0.15        # Alpha parameter for blend crossover
  gaussian_sigma: 0.3      # Sigma for Gaussian mutation
  gaussian_indpb: 0.3      # Independent probability for Gaussian mutation

# Fitness objectives (weights: 1.0 = maximize, -1.0 = minimize)
FITNESS:
  weights: [1.0]           # Single objective for now (maximize)
  metrics:
    - KGE_discharge        # Kling-Gupta Efficiency for discharge
    # - KGE_crops          # Can add more objectives for multi-objective optimization
