"""Typing definitions for GEB."""

import numpy as np

type ArrayFloat32 = np.ndarray[tuple[int], np.dtype[np.float32]]
type ArrayFloat64 = np.ndarray[tuple[int], np.dtype[np.float64]]
type ArrayInt8 = np.ndarray[tuple[int], np.dtype[np.int8]]
type ArrayUint8 = np.ndarray[tuple[int], np.dtype[np.uint8]]
type ArrayInt16 = np.ndarray[tuple[int], np.dtype[np.int16]]
type ArrayUint16 = np.ndarray[tuple[int], np.dtype[np.uint16]]
type ArrayInt32 = np.ndarray[tuple[int], np.dtype[np.int32]]
type ArrayUint32 = np.ndarray[tuple[int], np.dtype[np.uint32]]
type ArrayInt64 = np.ndarray[tuple[int], np.dtype[np.int64]]
type ArrayUint64 = np.ndarray[tuple[int], np.dtype[np.uint64]]
type ArrayBool = np.ndarray[tuple[int], np.dtype[np.bool_]]
type ArrayDatetime64 = np.ndarray[tuple[int], np.dtype[np.datetime64]]

type TwoDArrayFloat32 = np.ndarray[tuple[int, int], np.dtype[np.float32]]
type TwoDArrayFloat64 = np.ndarray[tuple[int, int], np.dtype[np.float64]]
type TwoDArrayInt8 = np.ndarray[tuple[int, int], np.dtype[np.int8]]
type TwoDArrayInt16 = np.ndarray[tuple[int, int], np.dtype[np.int16]]
type TwoDArrayInt32 = np.ndarray[tuple[int, int], np.dtype[np.int32]]
type TwoDArrayInt64 = np.ndarray[tuple[int, int], np.dtype[np.int64]]
type TwoDArrayUint8 = np.ndarray[tuple[int, int], np.dtype[np.uint8]]
type TwoDArrayUint16 = np.ndarray[tuple[int, int], np.dtype[np.uint16]]
type TwoDArrayUint32 = np.ndarray[tuple[int, int], np.dtype[np.uint32]]
type TwoDArrayUint64 = np.ndarray[tuple[int, int], np.dtype[np.uint64]]
type TwoDArrayBool = np.ndarray[tuple[int, int], np.dtype[np.bool_]]

type ThreeArrayInt32 = np.ndarray[tuple[int, int, int], np.dtype[np.int32]]
type ThreeArrayInt64 = np.ndarray[tuple[int, int, int], np.dtype[np.int64]]
type ThreeDArrayUint32 = np.ndarray[tuple[int, int, int], np.dtype[np.uint32]]
type ThreeDArrayUint64 = np.ndarray[tuple[int, int, int], np.dtype[np.uint64]]
type ThreeDArrayFloat32 = np.ndarray[tuple[int, int, int], np.dtype[np.float32]]
type ThreeDArrayFloat64 = np.ndarray[tuple[int, int, int], np.dtype[np.float64]]
type ThreeDArrayBool = np.ndarray[tuple[int, int, int], np.dtype[np.bool_]]
