"""Typing definitions for GEB."""

import numpy as np

ArrayFloat32 = np.ndarray[tuple[int], np.dtype[np.float32]]
ArrayFloat64 = np.ndarray[tuple[int], np.dtype[np.float64]]
ArrayInt8 = np.ndarray[tuple[int], np.dtype[np.int8]]
ArrayUint8 = np.ndarray[tuple[int], np.dtype[np.uint8]]
ArrayInt16 = np.ndarray[tuple[int], np.dtype[np.int16]]
ArrayUint16 = np.ndarray[tuple[int], np.dtype[np.uint16]]
ArrayInt32 = np.ndarray[tuple[int], np.dtype[np.int32]]
ArrayUint32 = np.ndarray[tuple[int], np.dtype[np.uint32]]
ArrayInt64 = np.ndarray[tuple[int], np.dtype[np.int64]]
ArrayUint64 = np.ndarray[tuple[int], np.dtype[np.uint64]]
ArrayBool = np.ndarray[tuple[int], np.dtype[np.bool_]]
ArrayDatetime64 = np.ndarray[tuple[int], np.dtype[np.datetime64]]

TwoDArrayFloat32 = np.ndarray[tuple[int, int], np.dtype[np.float32]]
TwoDArrayFloat64 = np.ndarray[tuple[int, int], np.dtype[np.float64]]
TwoDArrayInt8 = np.ndarray[tuple[int, int], np.dtype[np.int8]]
TwoDArrayInt16 = np.ndarray[tuple[int, int], np.dtype[np.int16]]
TwoDArrayInt32 = np.ndarray[tuple[int, int], np.dtype[np.int32]]
TwoDArrayInt64 = np.ndarray[tuple[int, int], np.dtype[np.int64]]
TwoDArrayUint8 = np.ndarray[tuple[int, int], np.dtype[np.uint8]]
TwoDArrayUint16 = np.ndarray[tuple[int, int], np.dtype[np.uint16]]
TwoDArrayUint32 = np.ndarray[tuple[int, int], np.dtype[np.uint32]]
TwoDArrayUint64 = np.ndarray[tuple[int, int], np.dtype[np.uint64]]
TwoDArrayBool = np.ndarray[tuple[int, int], np.dtype[np.bool_]]

ThreeArrayInt32 = np.ndarray[tuple[int, int, int], np.dtype[np.int32]]
ThreeArrayInt64 = np.ndarray[tuple[int, int, int], np.dtype[np.int64]]
ThreeDArrayUint32 = np.ndarray[tuple[int, int, int], np.dtype[np.uint32]]
ThreeDArrayUint64 = np.ndarray[tuple[int, int, int], np.dtype[np.uint64]]
ThreeDArrayFloat32 = np.ndarray[tuple[int, int, int], np.dtype[np.float32]]
ThreeDArrayFloat64 = np.ndarray[tuple[int, int, int], np.dtype[np.float64]]
ThreeDArrayBool = np.ndarray[tuple[int, int, int], np.dtype[np.bool_]]
