name: publish conda

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: fcakyon/conda-publish-action@v1.3
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.CONDA }}
        platforms: 'win osx linux'