name: Ruff Error Count Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-ruff-errors:
    runs-on: ubuntu-latest
    env:
      RULES: ANN001,ANN002,ANN003,ANN201,ANN202,ANN204,ANN205,ANN206,D102,D103,D100,D107,D105,D101,D104,D102,D103,D105,D107,D100,D101,D104,D102,D103,D105,D107,D100,D101,D104,DOC201,DOC202,DOC402,DOC501,DOC502,ANN003,ANN205,ANN206
    steps:
      - name: Checkout main branch for baseline
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-branch

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          path: pr-branch

      - name: Install Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"

      - name: Run ruff on main (capture full output + per-rule stats)
        id: ruff_main
        run: |
          set -o pipefail
          cd main-branch
          # Run ruff, capture full output to file and compute per-rule stats (RULE COUNT)
          ruff check --preview --statistics --select "${RULES}" --output-format full . 2>&1 | tee ruff_main_full.txt || true
          # extract lines like: "<count> <RULE>  <message>" -> produce "RULE COUNT"
          awk '/^[[:space:]]*[0-9]+[[:space:]]+[A-Z0-9_]+/ {print $2" "$1}' ruff_main_full.txt > ruff_main_stats.txt || true
          # expose paths as step outputs for later steps
          echo "full_file=main-branch/ruff_main_full.txt" >> $GITHUB_OUTPUT
          echo "stats_file=main-branch/ruff_main_stats.txt" >> $GITHUB_OUTPUT

      - name: Run ruff on PR (capture full output + per-rule stats)
        id: ruff_pr
        run: |
          set -o pipefail
          cd pr-branch
          ruff check --preview --statistics --select "${RULES}" --output-format full . 2>&1 | tee ruff_pr_full.txt || true
          awk '/^[[:space:]]*[0-9]+[[:space:]]+[A-Z0-9_]+/ {print $2" "$1}' ruff_pr_full.txt > ruff_pr_stats.txt || true
          echo "full_file=pr-branch/ruff_pr_full.txt" >> $GITHUB_OUTPUT
          echo "stats_file=pr-branch/ruff_pr_stats.txt" >> $GITHUB_OUTPUT

      - name: Compare per-rule counts and print full PR errors for regressed rules
        run: |
          MAIN_STATS="main-branch/ruff_main_stats.txt"
          PR_STATS="pr-branch/ruff_pr_stats.txt"
          PR_FULL="pr-branch/ruff_pr_full.txt"

          # Ensure files exist to avoid errors
          [ -f "$MAIN_STATS" ] || touch "$MAIN_STATS"
          [ -f "$PR_STATS" ] || touch "$PR_STATS"
          [ -f "$PR_FULL" ] || touch "$PR_FULL"

          # Build union of rules seen in either run
          awk '{print $1}' "$MAIN_STATS" "$PR_STATS" | sort | uniq > all_rules.txt || true

          regressions=0
          while read -r rule; do
            [ -z "$rule" ] && continue
            base=$(awk -v r="$rule" '$1==r{print $2}' "$MAIN_STATS" | head -n1 || true)
            pr=$(awk -v r="$rule" '$1==r{print $2}' "$PR_STATS" | head -n1 || true)
            base=${base:-0}
            pr=${pr:-0}
            if [ "$pr" -gt "$base" ]; then
              regressions=$((regressions+1))
              echo "------------------------------------------------------------"
              echo "Regression detected for rule: $rule (main: $base -> pr: $pr)"
              echo "Full PR error lines for rule $rule:"
              # Print full lines from PR that reference the rule code
              grep -F "$rule" "$PR_FULL" || echo "(no matching lines found in PR full output for $rule)"
              echo ""
            fi
          done < all_rules.txt

          if [ "$regressions" -gt 0 ]; then
            echo "::error::New per-rule regressions introduced: $regressions"
            exit 1
          else
            echo "No new per-rule regressions introduced."
          fi

      - name: Final message
        if: success()
        run: echo "Ruff per-rule regression check passed."